title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  This site aggregrates all my previously written articles in one place

# social links
twitter_username: nananja_jeans
github_username:  nananjajeans





show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings


plugins:
 - jekyll-feed
 - jekyll-seo-tag
